'use client';
import {useEffect,useState} from 'react';

const areas=[
['01','Construction & Building','/projects/construction.jpg','Skilled teams for practical construction and building projects.'],
['02','Welding & Metal Fabrication','/projects/welding.jpg','Professional fabrication capability, coordinated around the work.'],
['03','Logistics & Transport','/projects/logistics.jpg','Reliable movement and logistics support for people and projects.'],
['04','Electrical & Plumbing','/projects/technical.jpg','Technical professionals brought together for essential installations.'],
['05','Project Management','/projects/team.jpg','Clear planning, team coordination and delivery from start to finish.']];
function Reveal(){useEffect(()=>{const ns=document.querySelectorAll('[data-r]');const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');o.unobserve(e.target)}}),{threshold:.1});ns.forEach(n=>o.observe(n));return()=>o.disconnect()},[]);return null}
type PortfolioItem={name:string;area:string;title:string;description:string;link:string;images:string[]};
export default function Home(){
const[menu,setMenu]=useState(false);
const[path,setPath]=useState<'skills'|'project'|'portfolio'>('skills');
const[scrolled,setScrolled]=useState(false);
const[sent,setSent]=useState(false);
const[portfolio,setPortfolio]=useState<PortfolioItem[]>([]);
const[portSent,setPortSent]=useState(false);
useEffect(()=>{const onScroll=()=>setScrolled(scrollY>36);onScroll();addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[]);
const handlePortfolioSubmit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fd.get('name'),area:fd.get('area'),title:fd.get('title'),description:fd.get('description'),link:fd.get('link')})})}catch{}setPortSent(true);(e.target as HTMLFormElement).reset()};
return <main><Reveal/><div className="scrollLine"/>
<nav className={scrolled?'navScrolled':''}><a className="brand brandPrime" href="/"><img src="/fredems-prime-logo.png" alt="FREDEMS Prime"/><span><small>YOUNG PROFESSIONALS NETWORK</small></span></a><div className="links"><a className="backPrime" href="/">← FREDEMS Prime</a><a href="#about">About</a><a href="#areas">Core Areas</a><a href="#process">How We Work</a><a href="#join" onClick={()=>{setPath('portfolio');setPortSent(false)}}>Portfolio</a><a href="#vision">Vision</a></div><a className="navCta" href="#join">Join the network ↗</a><button className="menu" aria-expanded={menu} aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?'×':'☰'}</button>{menu&&<div className="mobile"><a className="mobileBack" href="/">← Back to FREDEMS Prime</a>{[['#about','About'],['#areas','Core Areas'],['#process','How We Work'],['#join','Portfolio'],['#join','Join']].map((i,j)=><a key={j} href={i[0]} onClick={()=>setMenu(false)}>{i[1]}</a>)}</div>}</nav>
<section className="hero"><div className="shade"/><div className="heroCopy" data-r><span className="pill">An initiative of FREDEMS Prime Limited Company</span><h1>Young professionals.<br/><em>Real projects.</em></h1><p>Building skills, creating opportunities and delivering projects through a trusted network of ambitious professionals.</p><div className="actions"><a href="#join">Join the network</a><a href="#areas">Explore our expertise →</a></div><small>CONNECTING SKILLS · MANAGING PROJECTS · CREATING OPPORTUNITIES</small></div><div className="pip"><div/><img src="/pip-mascot.png" alt="Pip, the FREDEMS project mascot"/><span><small>MEET PIP</small><b>Your project guide.</b></span><i/></div></section>
<section id="about" className="intro" data-r><div><label>WHO WE ARE</label><h2>One network.<br/><em>Shared ambition.</em></h2></div><div><p>FREDEMS brings skilled and ambitious young professionals together to collaborate, develop practical expertise and execute projects professionally.</p><a href="#process">Discover how we work ↗</a></div></section>
<section className="collabStory" data-r><figure className="collabMain"><img src="/young-design-team.png" alt="Young Ghanaian professionals collaborating over project plans"/><span>DESIGNING TOGETHER</span></figure><figure className="collabSmall"><img src="/projects/team.jpg" alt="A professional team sharing ideas around a table"/><span>ONE TEAM · MANY SKILLS</span></figure><div className="collabCopy"><label>IDEAS BECOME PROJECTS</label><h2>Bring people around<br/><em>the same table.</em></h2><p>Good projects start with shared understanding. The network creates space for young professionals to review ideas, combine perspectives and shape a practical path forward.</p><div><span>Discuss the brief</span><i>→</i><span>Develop the design</span><i>→</i><span>Coordinate delivery</span></div></div></section>
<section className="stats" data-r><header><label>OUR FOUNDATION</label><h2>Built for practical progress</h2></header><div><article><b>05</b><span>Core professional areas</span></article><article><b>01</b><span>Connected project network</span></article><article><b>360°</b><span>Planning to completion</span></article><article><b>∞</b><span>Room to learn and grow</span></article></div></section>
<section className="valueSection"><header data-r><label>WHAT THE NETWORK CREATES</label><h2>Professional growth with<br/><em>practical purpose.</em></h2><p>The network is designed around real collaboration—helping people strengthen their expertise while giving projects the structure and coordination they need.</p></header><div className="valueGrid"><article data-r><span>01</span><i>◇</i><h3>Collaborative teams</h3><p>Different skills come together around a shared brief, clear responsibilities and a common outcome.</p></article><article data-r><span>02</span><i>✦</i><h3>Practical expertise</h3><p>Professionals develop through meaningful participation, hands-on problem solving and continuous learning.</p></article><article data-r><span>03</span><i>◎</i><h3>Coordinated delivery</h3><p>Planning, communication and professional standards guide the work from opportunity to completion.</p></article><div className="valueOrb" aria-hidden="true"><b>F</b><span/><span/><span/></div></div></section>
<section id="areas" className="areas"><header data-r><div><label>OUR CORE AREAS</label><h2>Expertise that gets<br/><em>work moving.</em></h2></div><p>Explore the professional disciplines within the network—connected by a shared commitment to quality, coordination and practical delivery.</p></header><div className="cards">{areas.map((a,i)=><article data-r className={i===4?'last':''} key={a[0]}><figure><img src={a[2]} alt=""/><span>{a[0]}</span><i>↗</i></figure><div><h3>{a[1]}</h3><p>{a[3]}</p><a href="#join">Connect with this area →</a></div></article>)}</div></section>
<section id="process" className="process"><div data-r><label>HOW WE WORK</label><h2>From opportunity<br/>to <em>completion.</em></h2><p>FREDEMS connects clients and opportunities with the right professionals, coordinates teams and promotes strong standards throughout execution.</p><small>PLAN → BUILD → DELIVER</small></div><aside>{[['01','Understand the project','We begin with the need, scope and intended outcome.'],['02','Connect the right skills','The network brings together professionals suited to the work.'],['03','Coordinate execution','Clear roles, communication and project management keep delivery on track.'],['04','Deliver and improve','We complete professionally, learn continuously and grow together.']].map(s=><article data-r key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div><i>↗</i></article>)}</aside></section>
<section id="vision" className="vision" data-r><img src="/projects/team.jpg" alt="Young professionals collaborating"/><div><label>OUR VISION</label><h2>A trusted platform to<br/><em>grow together.</em></h2><p>Where young professionals combine skills, expertise and opportunities to build businesses and execute meaningful projects.</p><small>START FOCUSED → DELIVER QUALITY → LEARN CONTINUOUSLY → EXPAND TOGETHER</small></div><i className="object"/></section>
<section id="join" className="join"><header data-r><label>TAKE THE NEXT STEP</label><h2>Let's build something<br/><em>meaningful.</em></h2><p>Choose your path and tell us where you would like to begin.</p></header><div className="joinCard" data-r><div className="joinInfo"><div className="tabs"><button className={path==='skills'?'active':''} onClick={()=>{setPath('skills');setSent(false)}}>I have skills</button><button className={path==='project'?'active':''} onClick={()=>{setPath('project');setSent(false)}}>I have a project</button><button className={path==='portfolio'?'active':''} onClick={()=>{setPath('portfolio');setSent(false);setPortSent(false)}}>Share your portfolio</button></div><label>{path==='skills'?'FOR YOUNG PROFESSIONALS':path==='project'?'FOR CLIENTS & PARTNERS':'SHOWCASE YOUR WORK'}</label><h3>{path==='skills'?'Bring your expertise. Find your team.':path==='project'?'Bring the opportunity. Meet the right team.':'Show what you can deliver.'}</h3><p>{path==='skills'?'Join a network designed for professional collaboration, practical development and meaningful project experience.':path==='project'?'Tell us what needs to be built, moved, fabricated, installed or coordinated.':'Upload projects you have worked on, share your expertise and let the network see what you can deliver.'}</p><span>✓ Practical expertise<br/>✓ Coordinated teams<br/>✓ Professional standards</span><img src="/pip-mascot.png" alt=""/></div>
{path==='portfolio'?(portSent?<div className="successState"><i>✓</i><label>PORTFOLIO ADDED</label><h3>Your work is now visible.</h3><p>Continue building your portfolio below.</p><button onClick={()=>setPortSent(false)}>Add another project</button></div>:<form className="portfolioFormInline" onSubmit={handlePortfolioSubmit}><div className="portfolioFormGrid"><label>Full name<input required name="name" placeholder="Your name" autoComplete="name"/></label><label>Professional area<select required name="area" defaultValue=""><option value="" disabled>Select an area</option>{areas.map(a=><option key={a[0]}>{a[1]}</option>)}</select></label><label>Project title<input required name="title" placeholder="e.g. Kitchen renovation wiring"/></label><label>Project description<textarea required name="description" rows={3} placeholder="Briefly describe the project, your role and the outcome"/></label><label>Portfolio link (optional)<input name="link" type="url" placeholder="https://..."/></label><label>Upload images<input name="files" type="file" accept="image/png,image/jpeg,image/gif,image/webp" multiple /></label></div><button type="submit">Submit portfolio <span>↗</span></button></form>):sent?<div className="successState"><i>✓</i><label>INTEREST RECEIVED</label><h3>Thanks for reaching out.</h3><p>Your details have been captured for this demonstration. FREDEMS can connect this form to its preferred inbox or project system when ready.</p><button onClick={()=>setSent(false)}>Send another response</button></div>:<form onSubmit={async(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fd.get('name'),email:fd.get('email'),area:fd.get('area'),message:fd.get('message')})})}catch{}setSent(true)}}><label>Full name<input required placeholder="Your name" autoComplete="name" name="name"/></label><label>Email address<input required type="email" placeholder="you@example.com" autoComplete="email" name="email"/></label><label>Professional or project area<select required defaultValue="" name="area"><option value="" disabled>Select an area</option>{areas.map(a=><option key={a[0]}>{a[1]}</option>)}</select></label><label>Tell us a little more<textarea required rows={4} placeholder="A short summary is enough" name="message"/></label><button>Send your interest <span>↗</span></button><small>Expression of interest only. No open role or project guarantee is implied.</small></form>}</div></section>
<footer><div><span className="brand brandPrime"><img src="/fredems-prime-logo.png" alt="FREDEMS Prime"/><span><small>YOUNG PROFESSIONALS & PROJECTS NETWORK</small></span></span><h3>Building Skills.<br/>Creating Opportunities.<br/>Delivering Projects.</h3><aside><a href="#about">About</a><a href="#areas">Core Areas</a><a href="#process">How We Work</a><a href="#join">Join</a></aside></div><small>An initiative of FREDEMS PRIME LIMITED COMPANY <i>Connecting Skills. Managing Projects. Creating Opportunities.</i></small></footer>
</main>}
