'use client';
import {useEffect,useState} from 'react';
const companies=[
 {num:'01',name:'Fredems Real Estates',short:'Real Estates',text:'Real estate development, construction and property management.',image:'/projects/construction.jpg',color:'#d99b49',glyph:'▱'},
 {num:'02',name:'Fredems Agribusiness',short:'Agribusiness',text:'Sustainable agriculture and food processing.',image:'/projects/agribusiness.jpg',color:'#7ca35b',glyph:'◒'},
 {num:'03',name:'Fredems Logistics & Imports',short:'Logistics & Imports',text:'Reliable logistics, importation, distribution and international trade.',image:'/projects/logistics.jpg',color:'#4c75bc',glyph:'⇢'},
 {num:'04',name:'Fredems Enterprise',short:'Enterprise',text:'Strategic trade and business development.',image:'/young-design-team.png',color:'#8c64b7',glyph:'✦'}];
const values=[['F','Forward-Thinking','We embrace innovation, opportunity and new ways of creating lasting value.'],['R','Reliability','We honour our commitments and strive to be a dependable partner.'],['E','Excellence','We pursue high standards and deliver quality services and solutions.'],['D','Dedication','We approach every assignment with commitment, discipline and determination.'],['E','Ethics & Integrity','We conduct business with honesty, transparency, accountability and respect.'],['M','Meaningful Impact','We create opportunities, solve real problems and make a positive difference.'],['S','Service','We put clients at the centre with responsive, professional service.']];
const partners=[['Invest','Investors & investment partners','Explore promising ventures, projects and businesses within the FREDEMS ecosystem.'],['Build a venture','Strategic business partners','Collaborate on joint ventures, market expansion and commercial opportunities.'],['Supply or manufacture','Suppliers & manufacturers','Work with us across sourcing, importation, exportation and distribution.'],['Develop property','Real estate developers','Collaborate on development, management and real estate investment.'],['Grow agribusiness','Agribusiness partners','Develop sustainable agriculture, food production and value chains.'],['Move goods','Logistics & trade partners','Partner on transportation, cargo movement, delivery and international trade.']];
function Reveal(){useEffect(()=>{const n=document.querySelectorAll('[data-pr]');const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');o.unobserve(e.target)}}),{threshold:.1});n.forEach(x=>o.observe(x));return()=>o.disconnect()},[]);return null}
export default function PrimeHome(){const[active,setActive]=useState(0),[value,setValue]=useState(0),[partner,setPartner]=useState(0),[menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>40);f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);const company=companies[active];return <main className="prime"><Reveal/>
<nav className={`primeNav ${scrolled?'solid':''}`}><a href="/" className="primeBrand"><img src="/fredems-logo.jpeg" alt="FREDEMS logo"/><span>FREDEMS PRIME<small>LIMITED COMPANY</small></span></a><div className="primeLinks"><a href="#companies">Companies</a><a href="#purpose">Purpose</a><a href="#values">Values</a><a href="#partners">Partnerships</a><a href="/young-professionals">Young Professionals</a></div><a className="primeCta" href="#contact">Partner with us <span>↗</span></a><button className="primeMenu" aria-label="Menu" aria-expanded={menu} aria-controls="prime-mobile-navigation" onClick={()=>setMenu(!menu)}>{menu?'×':'☰'}</button>{menu&&<div id="prime-mobile-navigation" className="primeMobile"><a href="#companies" onClick={()=>setMenu(false)}>Companies</a><a href="#purpose" onClick={()=>setMenu(false)}>Purpose</a><a href="#partners" onClick={()=>setMenu(false)}>Partnerships</a><a href="/young-professionals">Young Professionals</a></div>}</nav>
<section className="primeHero"><div className="primeHeroBg"/><div className="primeHeroCopy" data-pr><span className="primeEyebrow">DIVERSIFIED BUSINESS GROUP · GHANA</span><h1>One group.<br/>Many industries.<br/><em>Meaningful impact.</em></h1><p>FREDEMS turns opportunities into trusted solutions and sustainable ventures across real estate, agribusiness, logistics, trade and emerging businesses.</p><div><a href="#companies">Explore our companies <b>↓</b></a><a href="#partners">Partner with FREDEMS <b>↗</b></a></div></div><div className="universe"><div className="core"><img src="/fredems-logo.jpeg" alt=""/><span>FREDEMS<br/>PRIME</span></div><div className="orbit o1">{companies.map((c,i)=><button key={c.name} style={{'--accent':c.color} as React.CSSProperties} className={active===i?'active':''} onClick={()=>setActive(i)}><i>{c.glyph}</i><span>{c.short}</span></button>)}</div><div className="orbit o2"/><div className="orbit o3"/></div><div className="heroIndex"><span>EST. IN GHANA</span><i/><span>BUILT FOR AFRICA</span></div></section>
<section className="primeIntro" data-pr><div><span className="primeLabel">THE GROUP</span><h2>A connected ecosystem<br/>built to <em>create value.</em></h2></div><p>FREDEMS is a diversified business group based in Ghana, delivering trusted solutions across logistics, imports, real estate, agribusiness, consulting, trading and emerging ventures.</p></section>
<section id="companies" className="companyJourney" style={{'--company':company.color} as React.CSSProperties}><header data-pr><span className="primeLabel">OUR FAMILY OF COMPANIES</span><h2>Four businesses.<br/><em>One ambition.</em></h2></header><div className="divisionTiles" data-pr>{companies.map((c,i)=><button key={c.name} style={{'--tile':c.color} as React.CSSProperties} className={active===i?'active':''} onClick={()=>setActive(i)}><span>{c.glyph}</span><i>↗</i><b>{c.short}</b><p>{c.text}</p></button>)}</div><div className="companyStage"><div className="companyTabs">{companies.map((c,i)=><button key={c.name} className={active===i?'active':''} onClick={()=>setActive(i)}><span>{c.num}</span><b>{c.short}</b></button>)}</div><div className="companyVisual"><img key={company.image} src={company.image} alt=""/><span>{company.glyph}</span><i>{company.num} / 04</i></div><div className="companyCopy"><span>{company.name}</span><h3>{company.text}</h3><p>Part of the FREDEMS ecosystem—connected by trusted service, professional standards and sustainable growth.</p><a href="#contact">Discuss an opportunity <b>↗</b></a></div></div></section>
<section id="purpose" className="purpose"><div className="purposeImage" data-pr><img src="/hero-ghana.jpeg" alt="Aerial view of business activity in Ghana"/><div className="mapPulse"><i/><i/><i/></div></div><div className="purposeCopy" data-pr><span className="primeLabel">OUR PURPOSE</span><div className="purposeBlock"><b>MISSION</b><h2>Create value through trusted services, innovative solutions and sustainable businesses.</h2><p>Empowering people, strengthening communities and driving economic growth.</p></div><div className="purposeBlock"><b>VISION</b><h2>A leading African business group with global relevance.</h2><p>Transforming opportunities into sustainable ventures and meaningful impact.</p></div></div></section>
<section id="values" className="values"><header data-pr><span className="primeLabel">WHAT GUIDES US</span><h2>The values inside<br/><em>FREDEMS.</em></h2></header><div className="valueExperience"><div className="valueLetters">{values.map((v,i)=><button className={value===i?'active':''} onClick={()=>setValue(i)} key={`${v[0]}${i}`}>{v[0]}</button>)}</div><div className="valueMeaning" data-pr><span>0{value+1}</span><h3>{values[value][1]}</h3><p>{values[value][2]}</p><div className="valueCube"><i/><i/><i/></div></div></div></section>
<section id="partners" className="partners"><header data-pr><span className="primeLabel">COLLABORATION</span><h2>How would you like<br/>to work with <em>FREDEMS?</em></h2></header><div className="partnerFinder"><div className="partnerOptions">{partners.map((p,i)=><button key={p[0]} className={partner===i?'active':''} onClick={()=>setPartner(i)}><i>{String(i+1).padStart(2,'0')}</i><span>{p[0]}</span><b>↗</b></button>)}</div><div className="partnerAnswer" data-pr><span>YOUR PATH</span><h3>{partners[partner][1]}</h3><p>{partners[partner][2]}</p><a href="#contact">Start this conversation <b>↗</b></a></div></div></section>
<section className="youngPortal"><div className="youngImage"><img src="/young-design-team.png" alt="Young professionals collaborating"/></div><div className="youngCopy" data-pr><span>AN INITIATIVE OF FREDEMS PRIME</span><h2>Young minds.<br/><em>Real projects.</em></h2><p>The Young Professionals & Projects Network connects ambitious talent with practical expertise, coordinated teams and meaningful opportunities.</p><a href="/young-professionals">Enter the network <b>↗</b></a></div><img className="portalPip" src="/pip-mascot.png" alt="Pip, the Young Professionals project guide"/></section>
<section id="contact" className="primeContact"><div className="contactIntro" data-pr><span className="primeLabel">LET'S BUILD TOGETHER</span><h2>Bring the opportunity.<br/>We’ll bring the <em>ecosystem.</em></h2><p>Whether you want to invest, build a venture, supply, trade or collaborate, start with the conversation that fits your opportunity.</p><div className="contactTopics"><a href="mailto:info@fplcgroup.com?subject=Investment%20partnership">Investment</a><a href="mailto:info@fplcgroup.com?subject=Business%20partnership">Business partnership</a><a href="mailto:info@fplcgroup.com?subject=Supply%20and%20trade">Supply &amp; trade</a><a href="mailto:info@fplcgroup.com?subject=General%20enquiry">General enquiry</a></div></div><div className="contactHub" data-pr><div className="contactHubTop"><span>CONTACT FREDEMS</span><i>KUMASI · GHANA</i></div><div className="contactMethod"><span>01</span><div><small>CALL US</small><a href="tel:+233596291605">059 629 1605</a><a href="tel:+233593541366">059 354 1366</a></div><b>↗</b></div><a className="contactMethod emailMethod" href="mailto:info@fplcgroup.com?subject=FREDEMS%20Partnership%20Enquiry"><span>02</span><div><small>EMAIL US</small><strong>info@fplcgroup.com</strong></div><b>↗</b></a><div className="contactMethod"><span>03</span><div><small>VISIT US</small><strong>Ahinsan Estate<br/>Kumasi, Ghana</strong></div><b>↗</b></div><a className="contactPrimary" href="mailto:info@fplcgroup.com?subject=FREDEMS%20Partnership%20Enquiry">Start a partnership conversation <b>↗</b></a></div></section>
<footer className="primeFooter"><div className="primeBrand"><img src="/fredems-logo.jpeg" alt=""/><span>FREDEMS PRIME<small>LIMITED COMPANY</small></span></div><p>Trusted services. Innovative solutions.<br/>Sustainable businesses.</p><div><a href="#companies">Companies</a><a href="#partners">Partnerships</a><a href="/young-professionals">Young Professionals</a></div><small>© FREDEMS PRIME LIMITED COMPANY · fslcgroup.com</small></footer>
</main>}
