'use client';
import Link from 'next/link';
import { useEffect, useRef } from 'react';
const companies=[
{n:'01',name:'Real Estates',tag:'Spaces built for lasting value',accent:'#d7a85d',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85'},
{n:'02',name:'Agribusiness',tag:'Sustainable agriculture and food processing',accent:'#7fa36b',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=85'},
{n:'03',name:'Logistics & Imports',tag:'Reliable movement, distribution and trade',accent:'#e86f4a',image:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=85'},
{n:'04',name:'Enterprise',tag:'Strategic trade and business development',accent:'#8aa6d9',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=85'}];
function EcosystemOrb(){const ref=useRef<HTMLDivElement>(null);return <div className="orb-stage" ref={ref} aria-hidden="true" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;ref.current?.style.setProperty('--rx',`${-y*22}deg`);ref.current?.style.setProperty('--ry',`${x*30}deg`)}} onPointerLeave={()=>{ref.current?.style.setProperty('--rx','-8deg');ref.current?.style.setProperty('--ry','12deg')}}><div className="orb-aura"/><div className="orb-world"><div className="orb-core"><b>FSLC</b><small>ONE ECOSYSTEM</small></div><i className="ring ring-a"/><i className="ring ring-b"/><i className="ring ring-c"/>{['BUILD','GROW','MOVE','CREATE'].map((t,i)=><span key={t} className={`sat sat-${i+1}`}>{t}</span>)}</div></div>}
function MotionSystem(){useEffect(()=>{const els=[...document.querySelectorAll<HTMLElement>('[data-reveal]')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.14});els.forEach(e=>io.observe(e));const onScroll=()=>document.documentElement.style.setProperty('--progress',`${scrollY/(document.documentElement.scrollHeight-innerHeight)*100}%`);addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>{io.disconnect();removeEventListener('scroll',onScroll)}});return <div className="progress" aria-hidden="true"/>}
export default function Home(){return <main><MotionSystem/>
<nav className="nav"><Link href="/" className="brand"><span>F</span> FSLC</Link><div className="navlinks"><a href="#about">About</a><a href="#companies">Companies</a><Link href="/partnerships">Partnerships</Link><Link href="/contact">Contact</Link></div><Link href="/contact" className="pill">Talk to us ↗</Link></nav>
<section className="hero"><img className="hero-media" src="https://images.unsplash.com/photo-1592963216747-0fd7e68f7bf3?auto=format&fit=crop&w=2200&q=90" alt="Modern city architecture in Ghana"/><div className="hero-shade"/><div className="hero-grid"/><EcosystemOrb/><div className="hero-copy"><p className="eyebrow light hero-reveal r1">KUMASI · GHANA · AFRICA</p><h1 className="hero-reveal r2">Building businesses<br/>that move <em>life</em> forward.</h1><p className="lede hero-reveal r3">Trusted solutions across real estate, agribusiness, logistics, imports and strategic enterprise.</p><div className="actions hero-reveal r4"><a href="#companies" className="button primary magnet">Explore FSLC <span>↘</span></a><a href="#about" className="text-link">Our story ↓</a></div></div><div className="hero-index"><span>WE BUILD.</span><span>WE GROW.</span><span>WE MOVE.</span><strong>WE ARE FSLC.</strong></div><div className="scroll">SCROLL TO DISCOVER <i/></div></section>
<div className="ticker"><div>ONE GROUP <i/> REAL ESTATE <i/> AGRIBUSINESS <i/> LOGISTICS & IMPORTS <i/> ENTERPRISE <i/> ONE ECOSYSTEM <i/> ONE GROUP <i/> REAL ESTATE <i/> AGRIBUSINESS <i/> LOGISTICS & IMPORTS <i/> ENTERPRISE</div></div>
<section id="about" className="intro wrap" data-reveal><p className="eyebrow">WHO WE ARE</p><div><h2>Four businesses.<br/><span>One ambition.</span></h2><p>FREDEMS is a diversified Ghanaian business group creating trusted, innovative and sustainable solutions for people, communities and economic growth.</p><Link href="/about" className="arrow-link">Discover our story <span>↗</span></Link></div></section>
<section id="companies" className="family"><div className="section-head wrap"><p className="eyebrow light">OUR FAMILY OF COMPANIES</p><h2>Meet the family.</h2></div><div className="company-panels">{companies.map(c=><article key={c.n} className="company" style={{'--accent':c.accent,'--image':`url(${c.image})`} as React.CSSProperties}><div className="company-overlay"/><span>{c.n}</span><div><p>FREDEMS</p><h3>{c.name}</h3><small>{c.tag}</small><Link href={`/companies/${c.name.toLowerCase().replaceAll(' & ','-').replaceAll(' ','-')}`}>Explore company ↗</Link></div></article>)}</div></section>
<section className="system" data-reveal><div className="system-copy"><p className="eyebrow light">THE FSLC ECOSYSTEM</p><h2>Different industries.<br/><i>Shared momentum.</i></h2><p>Four focused businesses connected by a common standard: trusted service, sustainable thinking and meaningful impact.</p></div><div className="system-visual" aria-hidden="true"><div className="system-center">FSLC<small>GHANA</small></div>{companies.map((c,i)=><div className={`system-node node-${i+1}`} key={c.n}><b>{c.n}</b><span>{c.name}</span></div>)}<i className="orbit-line one"/><i className="orbit-line two"/></div></section>
<section className="purpose wrap" data-reveal><p className="eyebrow">OUR PURPOSE</p><div className="mission"><span>MISSION</span><p>To create value through trusted services, innovative solutions, and sustainable businesses that empower people, strengthen communities, and drive economic growth.</p></div><div className="mission muted"><span>VISION</span><p>To become a leading African business group with global relevance, transforming opportunities into sustainable ventures and meaningful impact.</p></div></section>
<section className="values"><div className="wrap"><p className="eyebrow light">WHAT GUIDES US</p><h2>FREDEMS, by our values.</h2><div className="value-row">{['Forward-thinking','Reliability','Excellence','Dedication','Ethics & Integrity','Meaningful Impact','Service'].map((v,i)=><div key={v}><b>0{i+1}</b><span>{v}</span></div>)}</div></div></section>
<section className="cta"><p className="eyebrow light">PARTNER WITH FREDEMS</p><h2>Have something<br/><i>big</i> in mind?</h2><p>There is a place for you within our ecosystem.</p><Link href="/contact" className="button primary">Let’s build it together ↗</Link></section>
<footer><div className="footer-mark">FSLC<span>.</span></div><div><p>FREDEMS SOLUTIONS<br/>LIMITED COMPANY</p><p>Ahinsan Estate<br/>Kumasi, Ghana</p></div><div><a href="mailto:info@fslcgroup.com">info@fslcgroup.com</a><a href="tel:+233596291605">+233 59 629 1605</a><a href="tel:+233593541366">+233 59 354 1366</a></div><small>© {new Date().getFullYear()} FSLC · fslcgroup.com</small></footer>
</main>}
