import Link from 'next/link';
const companyContent:Record<string,{name:string;kicker:string;copy:string;services:string[];image:string;accent:string}>={
'real-estates':{name:'Fredems Real Estates',kicker:'BUILDING VALUE INTO PLACE',copy:'Real estate development, construction and property management shaped around people, businesses and communities.',services:['Property development','Construction','Property management'],image:'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=2200&q=88',accent:'#d7a85d'},
'agribusiness':{name:'Fredems Agribusiness',kicker:'GROWING WHAT COMES NEXT',copy:'Sustainable agriculture and food processing that turns opportunity in the land into lasting value.',services:['Sustainable agriculture','Food production','Food processing'],image:'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=2200&q=88',accent:'#8db878'},
'logistics-imports':{name:'Fredems Logistics & Imports',kicker:'MOVING WHAT MATTERS',copy:'Reliable logistics, importation, distribution and international trade connecting goods with the places they need to be.',services:['Transportation & delivery','Importation & distribution','Cargo & international trade'],image:'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?auto=format&fit=crop&w=2200&q=88',accent:'#e86f4a'},
'enterprise':{name:'Fredems Enterprise',kicker:'TURNING OPPORTUNITY INTO ENTERPRISE',copy:'Strategic trade and business development designed to build partnerships, unlock markets and grow sustainable ventures.',services:['Strategic trade','Business development','Market expansion'],image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=2200&q=88',accent:'#8aa6d9'}};
function Header(){return <nav className="nav inner-nav"><Link href="/" className="brand"><span>F</span> FSLC</Link><div className="navlinks"><Link href="/about">About</Link><Link href="/#companies">Companies</Link><Link href="/partnerships">Partnerships</Link><Link href="/contact">Contact</Link></div><Link href="/contact" className="pill">Talk to us ↗</Link></nav>}
function Foot(){return <footer><div className="footer-mark">FSLC<span>.</span></div><div><p>ONE GROUP<br/>FOUR BUSINESSES</p><p>Ahinsan Estate<br/>Kumasi, Ghana</p></div><div><a href="mailto:info@fslcgroup.com">info@fslcgroup.com</a><a href="tel:+233596291605">+233 59 629 1605</a></div><small>© {new Date().getFullYear()} FREDEMS SOLUTIONS LIMITED COMPANY</small></footer>}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const last=slug.at(-1)||'';const company=companyContent[last];
if(company)return <main style={{'--page-accent':company.accent} as React.CSSProperties}><Header/><section className="page-hero company-hero"><img src={company.image} alt=""/><div/><p>{company.kicker}</p><h1>{company.name}</h1></section><section className="detail wrap"><p className="eyebrow">PART OF THE FSLC FAMILY</p><div><h2>{company.copy}</h2><div className="service-list">{company.services.map((s,i)=><p key={s}><b>0{i+1}</b>{s}</p>)}</div></div></section><section className="connection"><p className="eyebrow">ONE CONNECTED GROUP</p><h2>Independent expertise.<br/>Shared ambition.</h2><p>{company.name} is one of four businesses within FREDEMS Solutions Limited Company.</p><Link href="/#companies" className="button primary">Explore the FSLC family ↗</Link></section><Foot/></main>;
if(last==='about')return <main><Header/><section className="page-hero text-hero"><p className="eyebrow light">ABOUT FSLC</p><h1>Opportunity,<br/><i>made meaningful.</i></h1></section><section className="detail wrap"><p className="eyebrow">OUR GROUP</p><div><h2>FREDEMS is a diversified business group based in Ghana.</h2><p className="body-copy">We deliver trusted solutions across logistics, imports, real estate, agribusiness, consulting, trading and emerging ventures—bringing focused businesses together around one enduring ambition.</p></div></section><section className="purpose wrap"><div className="mission"><span>MISSION</span><p>To create value through trusted services, innovative solutions, and sustainable businesses that empower people, strengthen communities, and drive economic growth.</p></div><div className="mission muted"><span>VISION</span><p>To become a leading African business group with global relevance, transforming opportunities into sustainable ventures and meaningful impact.</p></div></section><Foot/></main>;
if(last==='partnerships')return <main><Header/><section className="page-hero text-hero"><p className="eyebrow light">COLLABORATION</p><h1>Let’s build<br/><i>forward.</i></h1></section><section className="detail wrap"><p className="eyebrow">PARTNER WITH US</p><div><h2>There’s a space for you within our ecosystem.</h2><p className="body-copy">We welcome investors, institutions, suppliers, developers, specialists and industry leaders ready to turn shared opportunity into meaningful impact.</p><div className="service-list">{['Strategic business partners','Investors & investment partners','Suppliers & manufacturers','Real estate developers','Agribusiness partners','Logistics & trade partners','Corporate & institutional partners','Professional & technology partners'].map((s,i)=><p key={s}><b>{String(i+1).padStart(2,'0')}</b>{s}</p>)}</div></div></section><Foot/></main>;
return <main><Header/><section className="page-hero text-hero"><p className="eyebrow light">CONTACT FSLC</p><h1>Start a<br/><i>conversation.</i></h1></section><section className="contact-grid wrap"><div><p className="eyebrow">REACH US</p><h2>Ahinsan Estate<br/>Kumasi, Ghana</h2><a href="mailto:info@fslcgroup.com">info@fslcgroup.com</a><a href="tel:+233596291605">+233 59 629 1605</a><a href="tel:+233593541366">+233 59 354 1366</a></div><form><label>Name<input name="name" required/></label><label>Email<input type="email" name="email" required/></label><label>Area of interest<select name="company"><option>FSLC Group</option>{Object.values(companyContent).map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Message<textarea name="message" rows={5} required/></label><button className="button primary">Send inquiry ↗</button></form></section><Foot/></main>}
